# generate .itp, .top and .gro from a DaemonSimulation
from ..old_simulation import Simulation
import datetime

def generate_top_monolith(sim: Simulation, path: str):
    """
    Unoptimized .top emitter that will dump the whole system state
    as a single .top file, including atom types and everything else

    WARNING: WIP
    """
    with open(path, "w") as f:
        f.write(
            f"; Generated by martini_daemon.helpers.itpgen.py generate_top_monolith\n"
            f"; Generated on {datetime.datetime.now()}\n\n"
        )
        f.write("[defaults]\n1 2\n[atomtypes]\n")
        f.write(
            "\n".join(
                f"{type} {mass} {charge} A 0.0 0.0"
                for type, (charge, mass) in sim.system._atom_types.items()
            ) + "\n"
        )
        f.write("[nonbond_params]\n")
        f.write(
            "\n".join(
                f"{t1} {t2} 1 {p1} {p2}"
                for (t1, t2), (p1, p2) in sim.system.nonbonded_force._nb_types
                if (
                    sim.system.nonbonded_force._used_atom_types.get(t1) is not None
                    and sim.system.nonbonded_force._used_atom_types.get(t2) is not None
                )
            ) + "\n"
        )
        f.write("[moleculetype]\nUNIVERSE 1\n")



        f.write("[system]\nMonolithic .top file\n[molecules]\nUNIVERSE 1\n")
