[package]
name = "martini_daemon"
version = "0.1.0+dev"
edition = "2024"

[lib]
name = "martini_daemon"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
chrono = "0.4.44"

[dependencies]
glam = "0.33.7"
pyo3 = "0.29.2"
numpy = "0.29.0"
rand = "0.10.2"
kdtree = "0.8.1"
ordermap = "1.2.2"
sortedlist-rs = "0.2.5"
pyo3-stub-gen = "0.23.0"
flate2 = { version = "1.1.10", features = ["zlib-rs"] }
logos = "0.16.1"
