[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "martini_daemon"
authors = []
description = ""
readme = "README.md"
requires-python = ">=3.11"
keywords = []
classifiers = []
dependencies = [
  "numpy",
  "openmm",
  "molly@git+https://github.com/aster31/molly#egg=molly&subdirectory=bindings/python",
]
dynamic = ["version"]

[project.scripts]
daemon = "martini_daemon.__main:main"

[tool.maturin]
module-name = "martini_daemon.__rust"
features = ["pyo3/extension-module"]
python-source = "."

[tool.ruff.lint]
extend-select = [
  "F", # Pyflakes
  "I", # Import sorting
  "UP", # Warn on older python features such as %
  "C4", # flag unneccessary iteration patterns
  "RET", # warn on useless else blocks and explicit "return None"
  "SIM", # simplifications
  "ANN", # missing type annotations
  "D" # warn on missing documentation
]
ignore = [
  "D203", # we want to blank lines after class
  "D212", # we want a formally "empty" line after """ in docstrings
]

[project.optional-dependencies]

test = [
  "pytest",
  "mdtraj",
]

docs = [
  "sphinx",
  "sphinx-autoapi",
  "sphinx-rtd-theme",
  "myst-parser"
]

dev = [
  "python-lsp-server",
  "ruff",
  "ty"
]

trr = [
  "mdtraj"
]
