# analysis helper for problems where a group of atoms can be permanently mapped
# into a "monomer" unit, and a graph of monomers

import sys
import numpy as np


def generate_mapping(initial_molecules: list[tuple[str, int, int]]):
    """
        From a list of each type of monomer and their number and number of
        atoms, generate a np array that maps each atom to their monomer index.

        Returns the number of monomers, number of atoms and the mapping, all
        based on the initial_molecules list.
    """
    total_monomers = sum([x for _, x, _ in initial_molecules])
    total_atoms = sum([x * y for _, x, y in initial_molecules])
    mapping = np.empty(total_atoms, np.uint32)
    atom = 0
    monomer = 0
    for _, monomer_count, atom_count in initial_molecules:
        for _ in range(monomer_count):
            mapping[atom:atom+atom_count] = monomer
            atom += atom_count
            monomer += 1
    return total_monomers, total_atoms, mapping


def read_monomer_graph(bond_frames: list[np.array], mapping: np.array):
    """
        bond_frames has to be a file read by BondReporter.read_bonds.
        mapping is a mapping generated by generate_mapping from this module.

        Returns: frames - a list of frames, each frame a numpy array
        of dimension (n_bonds, 2), but in this case it is between
        monomers, not between atoms and mapping - a list of what monomer
        each atom belongs to.

        The conversion can take a while, and since the primary
        function of this is to be used in run.py style "recipes"
        this prints progress information to stdout by default.

        The result graph can have multiple connections between monomers,
        if there are multiple bonds between the monomers. Bonds, constraints
        and virtual sites are considered bonds, based on how BondReporter
        reports it. In case of vsites, the virtual particle is considered
        bonded to all constructing particles.
    """
    # input data and uninitialized result
    # make a mapping atom -> monomer
    monomer_frames = []
    for frame in bond_frames:
        # bonds that are between different monomers
        cross_bonds = filter(
            lambda pair: pair[0] != pair[1],
            map(
                lambda pair: (mapping[pair[0]], mapping[pair[1]]),
                frame
            )
        )
        # create a np array for them
        monomer_frames.append(np.fromiter(
            cross_bonds,
            dtype=np.dtype((np.uint32, 2))
        ))
    return monomer_frames


def conversion(
    monomer_frames: list[np.array], start: int, end: int,
    bonds_per_monomer: int
):
    """
        Calculate the degree of conversion in a polymerization reaction.
        - monomer_frames is given by read_monomer_graph
        - Should be calculated for a specific monomer. Its index in the monomer
        list should be between start and end (start inclusive, end not).
        - 100% conversion is reached when all monomers between start and end
        have bonds_per_monomer bonds to other monomers (the other monomers
        can be, but don't have to be between start and end)
    """

    count = end - start
    max_bonds = bonds_per_monomer * count
    conversions = np.empty(len(monomer_frames), np.float32)
    for i, frame in enumerate(monomer_frames):
        conversion = sum(
            map(
                lambda bond:
                    (1 if bond[0] >= start and bond[0] < end else 0) +
                    (1 if bond[1] >= start and bond[1] < end else 0),
                frame
            )
        ) / max_bonds
        if i % 8 == 0:
            print(
                f"Calculating conversion for frame {i}. "
                f"Current conversion {conversion}"
            )
        conversions[i] = conversion
    return conversions


def bond_orders(
    
)

def _unroll(max: int, edge_array: np.array):
    """
        Converts a condensed (np.array of dimension (n_edges, 2)) list of
        edges representation of a graph of 0:max numbers as nodes to a python
        list of sets representation. Information on the multiplicity of bonds
        is lost.
    """
    graph = [set() for _ in range(max)]
    for edge in edge_array:
        graph[edge[0]].add(edge[1])
        graph[edge[1]].add(edge[0])
    return graph


def _find_cycles(graph, max_loop, path):
    """
        Returns a set[set[int]] of loops found starting at path.

        Recursive, slow, naive solution.

        Uses python's built in set semantics to deduplicate.
    """
    res = set()
    if len(path) > max_loop:
        # for performance reasons...
        return res
    neighbors: set[int] = graph[path[-1]]
    for neigh in neighbors:
        if len(path) >= 3 and neigh == path[0]:
            res.add(frozenset(path))
        elif neigh not in path:
            res |= _find_cycles(graph, max_loop, [*path, neigh])
    return res


def loop_analysis(n_monomers, monomer_frames, max_loop=10, progress=False):
    """
        Finds loops between monomers in each frame, up to max_loop in length.

        Does not consider how many bonds there are between a pair of monomers.

        Uses python's set semantics to deduplicate and the recursive and naive
        _find_cycles helper.

        Minimum loop size: 3, maximum loop size: max_loop.

        Can take a while, if progress=True, print updates to stdout to make
        the wait better.
    """
    # set of sets of ints, for each frame
    loops: list[set[frozenset[int]]] = [set() for _ in monomer_frames]

    # naive, slow solution: check for loops starting at each atom, use sets to
    # deduplicate
    for frame_index, frame in enumerate(monomer_frames):
        if progress and frame_index % 16 == 0:
            sys.stdout.write(f"\033[2K\rfinding loops frame {frame_index} of {len(monomer_frames)}")
        loop_set: set[frozenset[int]] = loops[frame_index]
        graph = _unroll(n_monomers, frame)
        for i in range(n_monomers):
            loop_set |= _find_cycles(graph, max_loop, [i])

    if progress:
        sys.stdout.write("\033[2K\r")
    return loops


def find_double_bonds(n_monomers, monomer_frames):
    """
        Finds pairs of monomers connected by exactly 2 bonds. Can be useful
        together with loop analysis to e.g. find 2 large loops, in cases
        where there is one bond normally connecting two monomers, but
        multifunctional monomers can be bonded to eachother twice at
        different ends.
    """
    doubles = [set() for _ in monomer_frames]

    for frame_index, frame in enumerate(monomer_frames):
        graph = [{} for _ in range(n_monomers)]
        for edge in frame:
            l = graph[edge[0]]
            r = graph[edge[1]]

            if l.get(edge[1]) is None:
                l[edge[1]] = 1
            else:
                l[edge[1]] += 1

            if r.get(edge[0]) is None:
                r[edge[0]] = 1
            else:
                r[edge[0]] += 1

        for li, l in enumerate(graph):
            for ri, order in l.items():
                if order == 2:
                    doubles[frame_index].add((li, ri) if li > ri else (ri, li))
    return doubles

# TODO chain analysis - find different types of linear chains
# TODO find n_mers
